# Generated by Django 2.2.3 on 2021-06-03 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extend', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('cel', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('civil_status', models.CharField(choices=[('S', 'Soltero'), ('M', 'Casado'), ('D', 'Divorsiado'), ('F', 'Union libre')], max_length=10)),
                ('heard_from', models.CharField(choices=[('F', 'Facebook'), ('R', 'Recomendacion'), ('T', 'Transito'), ('F', 'Otro')], max_length=10)),
                ('blood', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('pay_day', models.CharField(max_length=200)),
                ('medical_condition', models.TextField()),
                ('schedule', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acuatica.Levels')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
