# Generated by Django 3.2.3 on 2021-06-21 01:57

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acuatica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcode', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('visible', models.BooleanField()),
                ('size', models.CharField(choices=[('B', 'Grande'), ('M', 'Mediano'), ('S', 'Chico')], max_length=20)),
                ('measures', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=60)),
                ('branches', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Acuatica Urioste'), ('AJ', 'Ajustes Contables'), ('M', 'Mantenimineto'), ('T', 'Tiendita')], max_length=8, null=True)),
                ('limited_inventory', models.BooleanField()),
                ('contained_products', models.CharField(max_length=50)),
                ('minimum_amount', models.CharField(max_length=200)),
                ('max_amount', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
                ('browserdescription', models.CharField(max_length=100)),
                ('browserTitle', models.CharField(max_length=50)),
                ('friendly_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto'),
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantity', models.IntegerField()),
                ('date', models.DateField(blank=True)),
                ('sale', models.IntegerField()),
                ('comments', models.TextField()),
                ('cost', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acuatica.inventario')),
            ],
            options={
                'verbose_name_plural': 'Entradas y Salidas',
            },
        ),
    ]
